name: Check ModelRunner

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Format & Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
